[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*", "src-tauri"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.6.2"
hdk = "=0.5.2"
serde = "1.0"

[workspace.dependencies.cart]
path = "dnas/cart/zomes/coordinator/cart"

[workspace.dependencies.cart_integrity]
path = "dnas/cart/zomes/integrity/cart"