[package]
name = "cart"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cart"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
cart_integrity = { workspace = true }
